<?php
return [
	//planes
	'paga_con_paypal'=>'Pay with PayPal',
	//


	//politica_privacidad
	'titulo_politica_privacidad'=>'PRIVACY POLICY LABORA PLANET SAC',
	'subtitulo_politica_privacidad'=>'PERSONAL DATA PROTECTION',
	'descripcion1_politica_privacidad'=>'The purpose of this document is to regulate the policies and procedures that will be applicable in the handling of personal data information by LABORA PLANET SAC, according to Law No. 29733 Law on Protection of Personal Data promulgated by SUPREME DECREE N ° 003-2013 -JUS, published on March 22, 2013 and the Information Security Directive of October 11, 2013 of the Republic of Peru as well as Regulation (EU) 2016/679 of the European Parliament and of the Council of April 27, 2016.',
	'razon_politica_privacidad'=>'Business name:',
	'sub1politica_privacidad'=>'1. Object:',
	'sub2politica_privacidad'=>'2. Responsible:',
	'sub3politica_privacidad'=>'LABORA PLANET SOCIEDAD ANONIMA CLOSED - LABORAPLANET SAC.',
	'sub4politica_privacidad'=>' Web page:',
	'sub5politica_privacidad'=>'3. Data processing:',
	'sub6politica_privacidad'=>'The way to collect information from our users is from the moment of registration on our website.',
	'sub7politica_privacidad'=>'The information collected by LABORA PLANET SAC. in the provision of its services and in general in the development of its corporate purpose, it is mainly used to identify and maintain a user registry. We can also keep records of the interactions we have with our users, including the products, services and customer service we have provided. This includes interactions with our platform, such as when a user has viewed a page or clicked on a button. <br>In order to offer certain products or services, we can passively collect your GPS coordinates, when available from your device. Most modern devices, such as smartphones, will show a permission request when our platform requests data.',
	'sub8politica_privacidad'=>'When they contact us, we may collect personal information that is intrinsic to communication. For example, if you contact us by email, we will collect the email address used.',
	'sub9politica_privacidad'=>'The information we can collect or process is the following: Metadata: IP address, computer and connection information, reference web page, standard web log information, language settings, time zone, etc. <br>
Device information: device identifier, device type, device add-ons, hardware capabilities, etc.',
	'sub10politica_privacidad'=>'Actions: visited pages, pressed buttons, display time, keyword search, etc.',
	'sub11politica_privacidad'=>'The personal information of the user can be processed by our staff in any of our offices that can be located inside and outside of Peru.',
	'sub12politica_privacidad'=>'Links to other sites',
	'sub13politica_privacidad'=>'On our website, you will find links to third-party websites. These links may be ours or may appear as content generated by other users. These linked sites are not under our control and therefore, we are not responsible for their actions. Before providing your personal information through any other website, we recommend that you examine the terms and conditions of use of that website and its privacy policy.',
	'sub14politica_privacidad'=>'Treatments and General Purposes of the information:',
	'sub15politica_privacidad'=>'• Provide the services and / or products purchased directly. <br/>
• Promote and advertise activities, products and services. <br/>
• Make reports with the various administrative authorities of national control and surveillance, judicial policies or authorities, financial entities. <br/>
• Internal and / or commercial administrative purposes such as: Market research, accounting reports, statistical analysis and billing. <br/>
                            • Collection, storage, recording, use, circulation, processing, deletion of personal data and accounting records. <br>
                            • Correspondence For commercial, advertising and marketing purposes (Direct mail, massive). <br>
                            • To facilitate the creation of a User Agreement (see the Terms of Service for more information). <br>
                            • To provide technical or other support. <br>
                            • To promote our other programs, products or services that may be of interest to you (unless you have chosen not to receive such communications). <br>
                            • Fraud identification and prevention of money laundering and other criminal activities <br>
                            • Transmission of information and personal data in audit processes. <br>
                            • Share personal data with banks, companies that offer benefits to our users. <br>',
	'sub16politica_privacidad'=>'4. User Rights:',
	'sub17politica_privacidad'=>'• USERS are natural or legal persons whose personal data is collected, stored or used by the Data Controller. Users will have the following rights:',
	'sub18politica_privacidad'=>'• Know, update and rectify your personal data in front of the Responsible, when the data is partial, inaccurate, incomplete, divided, and misleading. In any case, the USERS are obliged to provide truthful information. <br/>
• Request proof of authorization granted to the Data Controller, unless expressly excepted as a requirement for the treatment. <br/>
• Be informed on request directed by the person responsible for the treatment regarding the use that has been given to your personal data. <br/>
• Revoke the authorization and / or request the deletion of the data when the Constitutional and legal principles, rights and guarantees are not respected in the Treatment, as long as THE USERS do not have a legal or contractual duty to remain in the database. <br/>
• Access free of charge to your personal data that have been subject to Treatment by the Responsible. <br/>',
	'sub19politica_privacidad'=>'5. Queries, data update and claims:',
	'sub20politica_privacidad'=>'USERS can consult the personal information that is registered in the LABORA PLANET SAC database.',
	'sub21politica_privacidad'=>'The query must be formulated by email: contacto@laboraplanet.com',
	'sub22politica_privacidad'=>'The consultation will be answered within a maximum period of ten (10) business days from the date of receipt of the same. When it is not possible to attend the query within said term, the interested party will be informed, stating the reasons for the delay and indicating the date on which their query will be attended, which in no case may exceed five (5) business days following the expiration of the first term.',
	'sub23politica_privacidad'=>'USERS who consider that the information contained in the database of LABORA PLANET SAC., Should be subject to correction, update or deletion, or when they notice the alleged breach of any of the duties contained in this document or in the law, may file a claim',
	'sub24politica_privacidad'=>'The claim must be made by email: contacto@laboraplanet.com',
	'sub25politica_privacidad'=>'The claim will be resolved within a period of no less than 10 days and will be communicated to the HOLDER by email.',
	'sub26politica_privacidad'=>'Users may only file a complaint with the regulatory bodies in charge at national or international level once the consultation or claim process has been exhausted before LABORA PLANET SAC.',
	'sub27politica_privacidad'=>'6. Security',
	'sub28politica_privacidad'=>'LABORA PLANET SAC. You have implemented reasonable security measures to protect the users personal information.',
	'sub29politica_privacidad'=>'We keep the information on secure servers, we use the SSL (Secure Socket Layer) protocol for the transmission of information, we limit access to personal information to employees, contractors or agents who need to know that information in order to transmit it store or process it , for this case we use a CONFIDENTIALITY CONTRACT.',
	'sub30politica_privacidad'=>'However, LABORA PLANET SAC cannot guarantee that unauthorized third parties can never exceed our security measures or use your personal information for improper purposes. In the event that any information in our possession or under our control is compromised as a result of a security breach, we will take reasonable steps to investigate the situation and, where appropriate, we will notify people whose information may have been affected and We will take other measures.',
	'sub31politica_privacidad'=>'7. Use of cookie',
	'sub32politica_privacidad'=>'When accessing our LABORA PLANET SAC applications, our web server may send a cookie to your device. Some cookies we use last only during your web or application session and expire when you close your web browser or exit the application.',
	'sub33politica_privacidad'=>'Other cookies are used to remind you when you use the Services again, that we can identify the number of unique visitors we receive, which allows us to ensure that we have sufficient capacity to accommodate all our users.
Remember that you have visited or used the Services before. This means Customizing elements of the promotional design or content of our applications, it also allows you to collect anonymous statistical information about how you use the Services (including the duration of your application or web session) and the location from which you get access to them, to that we can improve the Services and know which elements and functions of the Services are most popular with our users.
Most web and mobile device browsers are set to accept cookies automatically and by default. However, you can change your browser settings to prevent automatic acceptance of cookies, or to receive a notification every time a cookie is set.',
	'sub34politica_privacidad'=>'8. Modifications to the Privacy Policies:',
	'sub35politica_privacidad'=>'LABORA PLANET SAC reserves the right to make changes or updates to this Privacy Policy at any time.',
	'sub36politica_privacidad'=>'9. Acceptance:',
	'sub37politica_privacidad'=>'Users of the information accept the processing of their personal data in accordance with the terms of the Privacy Notice in terms and conditions, when providing their data and registering on the platform.',
	'sub38politica_privacidad'=>'10. Validity:',
	'sub39politica_privacidad'=>'This General Privacy Policy is effective from the date of its publication in the month of July 2019.',
	'sub40politica_privacidad'=>'Queries:',
	'sub41politica_privacidad'=>'Claims:',
	//fin

		//proposito
	'sub1proposito'=>'Concept',
	'sub2proposito'=>'Laboraplanet is an innovative digital technology platform with easy access in Spanish language that offers many online job opportunities.',
	'sub3proposito'=>'Access our platform, Optimize your professional profile, position yourself in the working world and move towards success!',
	'sub4proposito'=>'Purpose',
	'sub5proposito'=>'“We offer the possibility of working from home or anywhere in the world” using digital technology.',
	//fin

		//proyectoDetalle
	'sub1proyectoDetalle'=>'Budget:',
	'sub2proyectoDetalle'=>'Knowledge:',
	'sub3proyectoDetalle'=>'Description:',
	'sub4proyectoDetalle'=>'APPLY',
	'sub5proyectoDetalle'=>'CANCEL',
	//fin

	//proyectos
	'sub1proyectos'=>'My Requirements',
	'sub2proyectos'=>'• To edit your project, you must click on the yellow button with the pencil icon and then follow the steps, there you can also acquire the character of "URGENCY" in your project. <br/> <br/>
                                                   • For the contractor if you wish to delete your project, you must click on the red button. <br/> <br/>
                                                   • Projects that are in yellow background are those that are in the "URGENT" character.

',
	'sub3proyectos'=>'Find and manage all your requirements.',
	'sub4proyectos'=>'Title of the Requirement',
	'sub5proyectos'=>'Publication date',
	'sub6proyectos'=>"You haven't reviewed profiles yet.",
	'sub7proyectos'=>'published',
	'sub8proyectos'=>"You haven't reviewed profiles yet.",
	'sub9proyectos'=>'Published',
	'sub10proyectos'=>'You already reviewed some profiles.',
	'sub11proyectos'=>'Evaluating',
	'sub12proyectos'=>'You have a collaborator working on your requirement',
	'sub13proyectos'=>'Working',
	'sub14proyectos'=>'Requirement Completed',
	'sub15proyectos'=>'Finalized',
	'sub16proyectos'=>'Stateless',
	'sub17proyectos'=>'Click here to see the users applied <br/>
                            to your project and add agreements.',
	'sub18proyectos'=>'YOU CANNOT UPDATE YOUR REQUIREMENT, BECAUSE YOU ALREADY HAVE APPLICANTS',
	'sub19proyectos'=>'EDIT REQUIREMENT',
	'sub20proyectos'=>"Let's give the requirement a name:",
	'sub21proyectos'=>'Describe your requirement:',
	'sub22proyectos'=>'Tell us which category your requirement is close to:',
	'sub23proyectos'=>'• Maximum amount of knowledge 11',
	'sub24proyectos'=>'I want to use my own budget',
	'sub25proyectos'=>'BUY URGENCY',
	//fin

	//publicar_trabajo
	'sub1publicar_trabajo'=>'Choose a subcategory',
	'sub2publicar_trabajo'=>'The data you are trying to enter already exists as',
	'sub3publicar_trabajo'=>'Post your requirement',
	'sub4publicar_trabajo'=>'Describe your requirement',
	'sub5publicar_trabajo'=>'Tell us which category your requirement is close to',
	'sub6publicar_trabajo'=>'Maximum amount of knowledge 11',
	'sub7publicar_trabajo'=>'I want to use my own budget',
	'sub8publicar_trabajo'=>'Urgent? Stand out from others',
	'sub9publicar_trabajo'=>'No gracias',
	'sub10publicar_trabajo'=>'CONTINUE',
	'sub11publicar_trabajo'=>'Your requirement has been published successfully',
	'sub12publicar_trabajo'=>'Post new requirement',
	'sub13publicar_trabajo'=>'Register employer data',
	'sub14publicar_trabajo'=>'My requirements',
	'sub15publicar_trabajo'=>'List of workers',
	//fin

	//recibo
	'sub1recibo'=>'SHOPPING RECEIPT',
	'sub2recibo'=>'Collection Receipt:',
	'sub3recibo'=>'Order No. #:',
	'sub4recibo'=>'Authorization Number:',
	'sub5recibo'=>'Name of the buyer:',
	'sub6recibo'=>'Card Number:',
	'sub7recibo'=>'Order Date and Time:',
	'sub8recibo'=>'Transaction Amount:',
	'sub9recibo'=>'Transaction Currency:',
	'sub10recibo'=>'Comments:',
	'sub11recibo'=>'PRINT RECEIPT',
	'sub12recibo'=>'CONTINUE',
	//fin

	//recibo_error
	'sub1recibo_error'=>'SHOPPING RECEIPT',
	'sub2recibo_error'=>'Collection Receipt',
	'sub3recibo_error'=>'Order No.',
	'sub4recibo_error'=>'Card No.',
	'sub5recibo_error'=>'Order Date and Time',
	'sub6recibo_error'=>'Comments',
	'sub7recibo_error'=>'PRINT RECEIPT',
	'sub8recibo_error'=>'REINTENT',
	//fin

	//recibo_pago
	'sub1recibo_pago'=>'SHOPPING RECEIPT',
	'sub2recibo_pago'=>'Collection Receipt:',
	'sub3recibo_pago'=>'Order No. #:',
	'sub4recibo_pago'=>'Authorization No.',
	'sub5recibo_pago'=>'Name of the buyer',
	'sub6recibo_pago'=>'Card No.',
	'sub7recibo_pago'=>'Order Date and Time',
	'sub8recibo_pago'=>'Transaction Amount',
	'sub9recibo_pago'=>'Transaction Currency',
	'sub10recibo_pago'=>'Comments',
	'sub11recibo_pago'=>'PRINT RECEIPT',
	'sub12recibo_pago'=>'CONTINUE',
	//fin

	
	//recibo_pago_error
	'sub1recibo_pago_error'=>'SHOPPING RECEIPT',
	'sub2recibo_pago_error'=>'Collection Receipt:',
	'sub3recibo_pago_error'=>'Order No. #',
	'sub4recibo_pago_error'=>'Card No.',
	'sub5recibo_pago_error'=>'Order Date and Time',
	'sub6recibo_pago_error'=>'Comments',
	'sub7recibo_pago_error'=>'PRINT RECEIPT',
	'sub8recibo_pago_error'=>'REINTENT',
	//fin

	//recuperarC
	'sub1recuperarC'=>'Registry',
	'sub2recuperarC'=>'Set a new password',
	'sub3recuperarC'=>'Change',
	'sub4recuperarC'=>'To complete your password change, we send you a verification code to the email entered.',
	'sub5recuperarC'=>'Enter the verification code here',
	'sub6recuperarC'=>'Click here, if an email has not arrived.',
	'sub7recuperarC'=>'Enter your
                  <b> Email </b> and instructions will be sent to you!',
	'sub8recuperarC'=>'Send',
	//fin

	//seguridad
	'sub1seguridad'=>'Change Password',
	'sub2seguridad'=>'Drop out',
	'sub3seguridad'=>'DROP OUT',
	//fin


	// terminos_condiciones
	'sub1terminos_condiciones'=>'TERMS AND CONDITIONS OF THE LABORAPLANET SERVICE',
	'sub2terminos_condiciones'=>'El presente documento contiene los terminos y condiciones bajos los cuales el usuario de LABORAPLANET.COM,acepta utilizar nuestro sitio web o nuestros servicios.',
	'sub3terminos_condiciones'=>'1. Acceptance of the terms and conditions',
	'sub4terminos_condiciones'=>'By registering as “USER”, the Client accepts the security policy and the content of the terms and conditions of our website www.laboraplanet.com, mobile applications and the services we offer. <br/> <br/>
               Laboraplanet SAC reserves the right to modify the terms and conditions of its products and services. The provision of the service of our website <a href="https://laboraplanet.com/" target="_blank"> www.laboraplanet.com </a>, mobile applications and services for USERS is governed by the terms and conditions included below, which are understood as known and accepted by registered USERS.',
	'sub5terminos_condiciones'=>'2. Types of Users',
	'sub6terminos_condiciones'=>'They may make use of LABORAPLANET products and services, all natural or legal persons legally able to contract rights and obligations in the Peruvian territory and / or abroad according to the regulations in force in Latin America, North America and Europe. <br/> <br/>

               Unregistered customers will be called “VISITORS”, registered customers will be called “USERS”. <br/> <br/>

               Customers who wish to be USERS must carry out the registration as “USER” of LABORAPLANET prior to the use of any product or service through the web platform www.laboraplanet.com, completing the registration and profile. <br/> <br/>

               The USERS fulfill the roles of Employer (Natural or legal person requesting collaborators for the performance of a particular job or project) and Worker (Natural or legal person who is responsible for concretizing the work requested by an employer). <br/> <br/>

               If the USER decides not to accept all or part of these conditions, he must refrain from using the products and services of LABORAPLANET SAC.

',
	'sub7terminos_condiciones'=>'3. The services we offer',
	'sub8terminos_condiciones'=>"The laboraplanet.com site offers the human resource search service, as well as the search and execution of online work. In this sense, the worker's mission is to develop a specific project and the employer must pay the first for such service. Both agents will interact according to the terms and conditions of the service contemplated in this document. The service includes the maintenance of the laboraplanet.com site, which allows to develop agreements, provide conformities of the work performed and make the corresponding payments online. <br/> <br/>

                    In cases where controversies may arise between the parties. LABORAPLANET, offers the service of arbitration and conflict resolution with an additional cost. To provide an optimal and impartial service LABORAPLANET is based on the following data: <br/> <br/>

                    • The content of the initial requirement provided at the time of project publication. <br/>
• The history of agreements registered on this platform. <br/>
• Attachments. <br/> <br/>


All of them made only within this site. Any other agreement outside LABORAPLANET will not be considered. <br/> <br/>

Likewise, LABORAPLANET, IS NOT RESPONSIBLE for the services or obligations provided between the users or for the hidden defects that may arise as a result of the agreements between the parties, even less for the failures of the service that may arise after the delivery thereof. < br /> <br/>

LABORAPLANET is not affiliated, endorsed or sponsored by any external provider. <br/>

",
	'sub9terminos_condiciones'=>'4. Membership and taxes applied',
	'sub10terminos_condiciones'=>'Acquiring membership in LABORAPLANET is voluntary, when initially registering USERS obtain the Free plan, If USERS need to acquire benefits from the plans they should visit the <a href="https://laboraplanet.com/planes"> https: / /laboraplanet.com/planes </a> <br/> <br/>

                If the user decides to subscribe to one of our plans, said subscription must be made minimum for one (1) month and maximum for 12 months, the term is not required and the USER can complete the membership service at the time he decides. < br /> <br/>

                The payment of the membership is made once the subscription type of the membership in the platform is confirmed, it is immediate payment and is debited from the credit card or the payment method that the USER determines. <br/> <br />

                Regarding the commission The employer must pay a cost equivalent to 4% of the value defined by the work performed, which will be debited from the form of payment chosen by the USER. On the other hand, the commission to be paid by the worker is proportional to the relationship he develops with the employer. This means that when you start a relationship with an employer, it will be 19%. When the worker has received USD 300 from the employer, the commission will become 9.9%, and when the value paid exceeds USD 3000, the commission value will only be 4.9% :) <br/> <br/>

                LABORAPLANET may change the prices indicated above without prior notice. <br/> <br/>

                However, the products and / or services requested in advance by the USER will be canceled at the values ​​in force on the day they are acquired. <br/> <br/>

                To homogenize the payment currency, it will be used as the official currency, DOLLARS ($), in case the transaction is carried out in a currency other than Dollars, the exchange rate in force on the day of the transaction will be applied. <br/> <br/>

                To obtain help in case of any doubt regarding the billing or payment, the USER may contact the email payments@laboraplanet.com

',
    'sub11terminos_condiciones'=>'5. Means of payment',
    'sub12terminos_condiciones'=>'The USER can use the following means: Debit Card and VISA, PAYPAL or Electronic Transfer Credit Cards. <br/> <br/>


                    LABORAPLANET may request additional information from the USERS to verify that the payments have been made by the cardholder and / or account. <br/> <br/>

                    Once the “employer” provides compliance with the work done, LABORAPLANET releases the AMOUNT IN CUSTODY and proceeds to pay the worker by depositing into his LABORAPLANET account. The worker may withdraw his money as follows: 1 time per month when his plan is free, 2 times per month when his plan is platinum and at any time if his plan is Golden. <br/>',
    'sub13terminos_condiciones'=>'6. User Obligation',
    'sub14terminos_condiciones'=>'• Use diligently, correctly, and in accordance with Moral, law and Public Order, the products and / or services of LABORAPLANET. <br/>
                   • Make the information provided in the development of the products and / or services provided personal and non-transferable. <br/>
                   • Recognize and protect the intellectual property rights or any type of LABORAPLANET, in execution of the products and / or services offered. <br/>
                   • Refrain from making unauthorized exploitation of LABORAPLANET products and / or services for themselves or for the benefit of third parties. <br/>
                   • Respond for damages and losses that LABORAPLANET, its workers, suppliers, customers, other users and third parties in general may suffer, as a result of the breach of these conditions or of the individuals that were applicable to the products and / or services of LABORAPLANET. <br/>',
    'sub15terminos_condiciones'=>'7. Intellectual and industrial property',
    'sub16terminos_condiciones'=>'The USER acknowledges and accepts that LABORAPLANET is the owner of each and every one of the intellectual property rights of the products and / or services offered through the computer market. <br/> <br/>

                    By way of example, said ownership includes: Each of the products and / or services by LABORAPLANET, as well as the information provided at the time of delivery and / or provision of the service; the methodology, structure, selection, arrangement and contents of the website, Messages, graphics, drawings, sound and / or image files, photographs, recordings, databases, technology, computer equipment, know-how, brands, signs badges, logos, domain names and, in general, any kind of creation or accessible material of LABORAPLANET. <br/> <br/>

                    The USER also recognizes and accepts the existence of intellectual property rights of third parties over the aforementioned elements, which he also undertakes to respect. <br/> <br/>

                    The only use that LABORAPLANET authorizes on its contents and / or services is due to the SOCIAL OBJECT, which does not allow the USERS to carry out, directly or indirectly, a commercial exploitation of the products, services, materials, elements or information obtained from through them. <br/> <br/>

                    Unless expressly authorized by LABORAPLANET, the USER may not reproduce, transform, modify, disassemble, reverse engineer, distribute, rent, lend, display, transmit, retransmit, digitize, translate, adapt, make available or allow public access to through any modality of public communication of any of the elements referred to in the preceding paragraphs. <br/>',
    'sub17terminos_condiciones'=>'8. Protection of personal data',
	'sub18terminos_condiciones'=>'The USER authorizes in a prior, express and informed manner to LABORAPLANET so that, directly or through its employees, consultants, advisors and / or third parties in charge of data processing to perform any operation or set of operations such as collection, storage, use , circulation, deletion, transfer and transmission (the “Treatment”) about your personal data, as well as the receipt of commercial information associated with LABORAPLANET, understood as any information linked or that may be associated with the USER (the “Personal Data”) for the Compliance with the obligations arising from these general conditions, The USER knows the optional nature of delivering or not to LABORAPLANET their sensitive data. <br/> <br/>

              Likewise, the USER authorizes in a prior, express and informed way to LABORAPLANET to transfer and / or transmit the Personal Data of the USER or allow their access, to third parties located in PERU or abroad for the fulfillment of the same purposes of This Instrument, even to countries that do not provide adequate levels of data protection. The USER acknowledges and accepts that the Processing of his Personal Data carried out outside the Peruvian territory may be governed by foreign laws. The USER acknowledges that he has been informed of the rights that assist him in his capacity as holder of Personal Data, among which are the following: <br/> <br/>

              i) know, update and rectify your Personal Data against LABORAPLANET or those who on behalf of it carry out the Processing of your Personal Data. <br/>
ii) Request proof of authorization granted to LABORAPLANET except when the law does not require it. <br/>
iii) Upon request, be informed about the use that has been given to your Personal Data, by LABORAPLANET or those who, on behalf of the latter, carry out the Processing of their Personal Data. <br/>
iv) Submit complaints to the competent authorities for violations of the Peruvian legal regime for the protection of personal data. <br/>
v) Revoke this authorization and / or request the deletion of your Personal Data when the competent authority determines that LABORAPLANET incurred in conduct contrary to the law and the Constitution. <br/>
vi) Access free of charge to your Personal Data that have been subject to Treatment. For the purposes required by law, LABORAPLANET has designated an email datospersonales@laboraplanet.com for attention to the USER in relation to matters related to your Personal Data.',
    'sub19terminos_condiciones'=>'9. Guarantees and responsibilities',
    'sub20terminos_condiciones'=>'LABORAPLANET carries out all the necessary efforts to guarantee the quality of the products and / or services. However, due to their nature, the obligations assumed by LABORAPLANET are of medium and not of result. With this precision, LABORAPLANET is professionally and legally responsible only for the products and / or the provision of the services described in this document, under the conditions and terms agreed here. <br/> <br/>

                    The USER accepts that LABORAPLANET collects and uses the information related to the interaction through the tool for statistical purposes as well as to strengthen and improve its operation. <br/> <br/>


                    The USER assumes entirely the risks derived from the decisions he makes about the management, administration and operation of his business, company, personnel, equipment, security systems and any other element that composes his personal or business activity. <br/> <br/>

                    LABORAPLANET is not responsible for the contents, data and information that each of the USERS enter in the fields and spaces to exchange information with other USERS offered by the page. THE USER accepts that all information is the sole responsibility of the person who originated said Content. This means that THE USER is directly responsible for the Content he uploads. <br/> <br/>

                    LABORAPLANET expressly disclaims liability in situations that could be considered as Force Majeure. It undertakes to put the means of solving these types of problems within the limits of its capacity. <br/> <br/>

                    Any claim that the USER wishes to file must do so in writing, to the following email reclamamos@laboraplanet.com <br/> <br/>

                    Said mail must contain the date of the event subject to claim, sufficient identification of the USER and reasons for the claim. LABORAPLANET undertakes to review and answer each of these claims. <br/>

',
    'sub21terminos_condiciones'=>'10. Relationship between Laboraplanet and the User',

    'sub22terminos_condiciones'=>'In accordance with the nature and purpose of these general conditions, it is understood that neither LABORAPLANET nor the USER has a corporate spirit and that its conclusion of this agreement does not imply the constitution of a different legal entity, in fact or in law, nor does it imply the payment of contributions to create equity, fund or common capital of any kind, so that each of them maintains its independence and autonomy. <br/> <br/>

                    Additionally, LABORAPLANET nor the USER acquires the representation of the other, for judicial or extrajudicial purposes, nor does it constitute a solidarity or guarantee agreement regarding the claims that third parties may present to any of them. <br/> <br/>

                    If civil, criminal, labor, fiscal, disciplinary or any other claims against LABORAPLANET or the USER are presented against a party for concepts derived from the execution of the present and that exclusively compromise the responsibility of the other, this or that undertakes to keep the required party harmless. <br/>

',
    'sub23terminos_condiciones'=>'11. Cancellation or suspension of registration',
    'sub24terminos_condiciones'=>'The USER accepts that LABORAPLANET, at its discretion, may cancel or suspend the right conferred on the use of the www.laboraplanet.com WEBSITE and of the Mobile Applications, Information, Services and Content, provided in the same, being able to do it at any time, according to the determination that LABORAPLANET discretionary makes in this regard, proceeding in case it applies to the settlement of this. The USER accepts that LABORAPLANET will not have any responsibility before him or third parties arising from the cancellation or suspension of his access to the WEBSITE www.laboraplanet.com and Mobile applications.',
	//fin





	// trabajadores
	'sub1trabajadores'=>'nationality',
	'sub2trabajadores'=>'Select...',
	'sub3trabajadores'=>'Without nationality',
	'sub4trabajadores'=>'Price per hour',
	'sub5trabajadores'=>'No profile',
	'sub6trabajadores'=>'Member since',
	'sub7trabajadores'=>'Certifications',
	'sub8trabajadores'=>'Knowledge',
	'sub9trabajadores'=>'Recognition',
	'sub10trabajadores'=>'Platform Level: Level',
	'sub11trabajadores'=>'Contract',
	'sub12trabajadores'=>'Add to Favorites',
	'sub13trabajadores'=>'Contact',
	'sub14trabajadores'=>'Add to Favorites',
	'sub15trabajadores'=>'Contact',

	//fin

		//trabajadores_certificados
	'sub1trabajadores_certificados'=>'Category',
	'sub2trabajadores_certificados'=>'NO PROFILE',
	//fin

	//trabajadores_paginate
	'sub1trabajadores_paginate'=>'Without nationality',
	'sub2trabajadores_paginate'=>'Price per hour',
	'sub3trabajadores_paginate'=>'No profile',
	'sub4trabajadores_paginate'=>'Member since',
	'sub5trabajadores_paginate'=>'Certifications',
	'sub6trabajadores_paginate'=>'Knowledge',
	'sub7trabajadores_paginate'=>'Recognition',
	'sub8trabajadores_paginate'=>'Platform Level: Level',
	'sub9trabajadores_paginate'=>'Contract',
	'sub10trabajadores_paginate'=>'Add to Favorites',
	'sub11trabajadores_paginate'=>'Contact',
	'sub12trabajadores_paginate'=>'Add to Favorites',
	'sub13trabajadores_paginate'=>'Contact',
	//fin

		//trabajos
	'sub1trabajos'=>'Request',
	'sub2trabajos'=>'My proposals',
	'sub3trabajos'=>'Skills Requirement',
	'sub4trabajos'=>'The client has not yet reviewed your proposal.',
	'sub5trabajos'=>'Pending',
	'sub6trabajos'=>'The customer has seen your proposal.',
	'sub7trabajos'=>'The customer has reviewed your profile.',
	'sub8trabajos'=>'Evaluation',
	'sub9trabajos'=>'You are hired in this requirement.',
	'sub10trabajos'=>'Hired',
	'sub11trabajos'=>'You have concluded the requirement with this client.',
	'sub12trabajos'=>'Finalized',
	'sub13trabajos'=>'My proposal',
	'sub14trabajos'=>'Requirement Name',
	'sub15trabajos'=>'Presentation',
	'sub16trabajos'=>'Economic proposal',
	'sub17trabajos'=>'He will finish the work in',
	'sub18trabajos'=>'Edit',
	'sub19trabajos'=>'Save',
	'sub20trabajos'=>'Cancel',
	'sub21trabajos'=>'Close',
	'sub22trabajos'=>'Employer Profile',
	'sub23trabajos'=>'Company address',
	'sub24trabajos'=>'Telephone Company',
	'sub25trabajos'=>'Company Identifier',
	'sub26trabajos'=>'PUBLISHED REQUIREMENTS',
	'sub27trabajos'=>'Employer Summary',	
	'sub28trabajos'=>'Close',
	'sub29trabajos'=>'Employer Profile',	
	'sub30trabajos'=>'PUBLISHED REQUIREMENTS',
	'sub31trabajos'=>'Employer Summary',	
	'sub32trabajos'=>'Close',
	'sub33trabajos'=>'DETAIL REQUIREMENT',	
	'sub34trabajos'=>'Company name',
	'sub35trabajos'=>'State',	
	'sub36trabajos'=>'Description',
	'sub37trabajos'=>'Publication date',	
	'sub38trabajos'=>'Requirement Budget',
	'sub39trabajos'=>'Requirement Time',	
	'sub40trabajos'=>'Knowledge',
	'sub41trabajos'=>'Close',	
	'sub42trabajos'=>'Add Agreement',
	'sub43trabajos'=>'Select',	
	'sub44trabajos'=>'Select a File',
	'sub45trabajos'=>'Add Publication',	
	'sub46trabajos'=>'Edit',
	'sub47trabajos'=>'Date',	
	'sub48trabajos'=>'Affair',	
	'sub49trabajos'=>'Agreement',	
	'sub50trabajos'=>'Records',	
	'sub51trabajos'=>'State',	
	'sub52trabajos'=>'Actions',	
	'sub53trabajos'=>'Close',	
	//fin

	//users
	'sub1users'=>'URGENT',	
	'sub2users'=>'Business',	
	'sub3users'=>'Description',	
	'sub4users'=>'Knowledge',	
	'sub5users'=>'Published',
	'sub6users'=>'Working',	
	'sub7users'=>'Evaluation',	
	'sub8users'=>'Time',	
	'sub9users'=>'Hours',	
	'sub10users'=>'Days',	
	'sub11users'=>'Weeks',	
	'sub12users'=>'Months',	
	'sub13users'=>'Budget',	
	//fin

		//verperfil
	'sub1verperfil'=>'Knowledge',
	'sub2verperfil'=>'I DO NOT ENTER KNOWLEDGE',
	'sub3verperfil'=>'LINKEDIN URL',
	'sub4verperfil'=>'I DO NOT ENTER LINKEDIN URL',
	'sub5verperfil'=>'WORK EXPERIENCES',
	'sub6verperfil'=>'I DO NOT RECORD DATA',
	'sub7verperfil'=>'EDUCATION',
	'sub8verperfil'=>'Technical',
	'sub9verperfil'=>'academic',
	'sub10verperfil'=>"Master's degree",
	'sub11verperfil'=>' Doctorates',
	'sub12verperfil'=>'I DO NOT RECORD DATA',
	'sub13verperfil'=>'Punctuation of',
	'sub14verperfil'=>'These are the skills to which',
	'sub15verperfil'=>'has submitted a validation exam',
	'sub16verperfil'=>'Does not have',
	'sub17verperfil'=>'No level',
	'sub18verperfil'=>'User',
	'sub19verperfil'=>'Qualification',
	'sub20verperfil'=>'Commentary',
	'sub21verperfil'=>'DOES NOT HAVE COMMENTS',
	//fin

	//video_chat
	'sub1video_chat'=>'VIDEO CHAT',
	//fin

		//vision
	'sub1vision'=>'Vision',
	'sub2vision'=>'To be the competitive and innovative technology company in the digital world in the promotion, search and execution of different types of online work.',
	//fin

		//vision_mision
	'sub1vision_mision'=>'Concept',
	'sub2vision_mision'=>'Laboraplanet is an innovative digital technology platform with easy access in Spanish language that offers many online job opportunities.',
	'sub3vision_mision'=>'Access our platform, Optimize your professional profile, position yourself in the working world and move towards success!',
	'sub4vision_mision'=>'Purpose',
	'sub5vision_mision'=>'“We offer the possibility of working from home or anywhere in the world” using digital technology.',
	'sub6vision_mision'=>'Misión',
	'sub7vision_mision'=>'We are a Technological company that facilitates the new way of working online offering quality processes and services for our clients.',
	'sub8vision_mision'=>'Vision:',
	'sub9vision_mision'=>'To be the competitive and innovative technology company in the digital world in the promotion, search and execution of different types of online work.',

	//fin

	//login
	'sub1login'=>'User not existing | Error in the data entered',
	//fin

	//register
	'sub1register'=>'I wish to hire',
	'sub2register'=>'I want to work',
	'sub3register'=>'Continue with facebook',
	'sub4register'=>'Continue with LinkedIn',
	'sub5register'=>'Continue with Google+',
	'sub6register'=>'Create your account to continue, if you are a user',
	'sub7register'=>'Log in',
	//fin

	//search
	'sub1search'=>'Work remotely independently. Self-employment !! Get client companies globally !!',
	'sub2search'=>'I want to be an independent contributor',
	'sub3search'=>'Work remotely from wherever you are. <br/> Show your genius to the world!',
	'sub4search'=>'START APPLICATION',
	'sub5search'=>'I want to hire collaborators',
	'sub6search'=>'Do you have an idea or requirement in mind? <br/> Publish your need, select and hire the best collaborator.',
	'sub7search'=>'START PROCESS',
	'sub8search'=>'Search Requirements',
	//fin

	//search_proyecto
	'sub1search_proyecto'=>'Search Requirements',
	'sub2search_proyecto'=>'Search and know the best requirements. Self-employment! undertake! The sky is the limit !…',
	'sub3search_proyecto'=>'Price',
	'sub4search_proyecto'=>'Less than 100 dollars',
	'sub5search_proyecto'=>'Between 100 and 500 dollars',
	'sub6search_proyecto'=>'More than 500 dollars',
	'sub7search_proyecto'=>'Requirement Status',
	'sub8search_proyecto'=>'Published',
	'sub9search_proyecto'=>'Evaluation',
	'sub10search_proyecto'=>'Working',
	'sub11search_proyecto'=>'Finalized',
	'sub12search_proyecto'=>'Find requirements',
	//fin

		//search_trabajadores
	'sub1search_trabajadores'=>'Price',
	'sub2search_trabajadores'=>'Less than 100 dollars',
	'sub3search_trabajadores'=>'Between 100 and 500 dollars',
	'sub4search_trabajadores'=>'More than 500 dollars',
	'sub5search_trabajadores'=>'Country',
	'sub6search_trabajadores'=>'DO YOU WANT TO AVOID SOME STEPS?',
	//fin

	//admin2
	'sub1admin2'=>'Notifications',
	'sub2admin2'=>'With your skills',
	'sub3admin2'=>'Postulate',
	'sub4admin2'=>'with your skills',
	'sub5admin2'=>'Postulate',
	'sub6admin2'=>'Notifications',
	'sub7admin2'=>'Postulate',
	'sub8admin2'=>'Active',
	'sub9admin2'=>'Inactive',
	'sub10admin2'=>'Profiles',
	'sub11admin2'=>'Collaborator',
	'sub12admin2'=>'Company / Employer',
	'sub13admin2'=>'Get Support',
	'sub14admin2'=>'Post Requirement',
	'sub15admin2'=>'How does it work',
	'sub16admin2'=>'Create Requirements',
	'sub17admin2'=>'My requirements',
	'sub18admin2'=>'Search requirements',
	'sub19admin2'=>'Certify knowledge',
	'sub20admin2'=>'© 2019 All Rights Reserved | LaboraPlanet',
	'sub21admin2'=>'SUPPORT',
	'sub22admin2'=>'LABORAPLANET COMMUNITY',
	'sub23admin2'=>'Contract',
	'sub24admin2'=>'You are about to hire ',
	'sub25admin2'=>', for the amount of',
	'sub26admin2'=>'To accept',
	'sub27admin2'=>'Cancel',
	//fin

]

?>