<?php

#PRUEBAS LABORAPLANET
define("merchantidtest","115015006");
define("usrtest","integraciones.visanet@necomplus.com");
define("pwdtest",'d5e7nk$M');
define("securityapitest","https://apitestenv.vnforapps.com/api.security/v1/security");
define("sessionapitest","https://apitestenv.vnforapps.com/api.ecommerce/v2/ecommerce/token/session/");
define("autorizationapitest","https://apitestenv.vnforapps.com/api.authorization/v3/authorization/ecommerce/");


#PRODUCCION  LABORAPLANET
define("merchantidprd","650164538");
define("usr","adminlabora@laboraplanet.com");
define("pwd",'@-tN@w4F');
define("securityapiprd","https://apiprod.vnforapps.com/api.security/v1/security");
define("sessionapiprd","https://apiprod.vnforapps.com/api.ecommerce/v2/ecommerce/token/session/");
define("autorizationapiprd","https://apiprod.vnforapps.com/api.authorization/v3/authorization/ecommerce/");



?>